### ISSUE TITLE
Possibility of making in_data unmutable?

### ISSUE THREAD

**Issue by stexa** [HEnquist/realfft#29]
It would be nice to use unmutable input data for the use in functions where I really don't want to allow changes to the data.
I see that the real data has to be transformed into complex by adding a zero as imaginary part.
But is there really no way of implementing this, other than making a copy of the data?

**Comment by HEnquist** [comment]
The input for odd length real-to-complex could easily be made unmutable. That one anyway copies the numbers to a scratch vector when it adds the zero imaginary part.
But the even length real-to-complex just passes the vector on to RustFFT, and RustFFT needs a mutable input. To make it unmutable, it would need to copy the input data to a scratch buffer and then give this one to RustFFT instead. So basically the input data must be copied, either behind the scenes by the library, or manually before calling process. This is not for free and I would prefer to skip it in the library since many users don't mind that the input is consumed.

**Comment by WalterSmuts** [comment]
@stexa Give [easyfft](https://docs.rs/easyfft/latest/easyfft/) a go. It's a bit more opinionated wrapping library that makes a couple of compromises, prioritising ergonomics.

**Comment by stexa** [comment]
Thanks, cool crate as well!
